dist: bionic
language: node_js
node_js:
  - 12
env:
  global:
    - NODE_ENV=production
before_script:
  - npm run lint
script:
  - npm run build
deploy:
  provider: pages
  edge: true
  local_dir: dist
  keep_history: false
  on:
    branch: master
