dist: bionic
language: node_js
node_js:
  - 12
env:
  global:
    - NODE_ENV=production
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
